### ISSUE TITLE
Paste doesn't work again

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#103]
https://github.com/rhysd/NyaoVim/commit/02711f4f5170e592ee42e2652cb3f67bee8875bb breaks paste.

The codes below `ipc.on('nyaovim:paste'` (https://github.com/rhysd/NyaoVim/blob/master/renderer/nyaovim-app.ts ) assumes the command is executed as `input`. But the commit changes it to a `normal` command, which breaks commands such as`command = '<C-o>"+gp';`.

### Expected Behavior

`cmd+v` should paste the text

### Actual Behavior

`cmd+v` doesn't do anything

### Steps to Reproduce (including precondition)
just paste with `cmd+v`

**Comment by rhysd** [comment]
Hmm, I guess `:execute 'normal!' "\<C-o>\"+gp"` is correct, right?
