### ISSUE TITLE
UNMET PEER DEPENDENCY react@^15.0.2

### ISSUE THREAD

**Issue by mdxprograms** [rhysd/NyaoVim#106]
I'm using node `7.2` with neovim `0.1.7`
I'm getting `UNMET PEER DEPENDENCY react@^15.0.2` on install

### Expected Behavior

Expect to install successfully with `npm i -g nyaovim`

### Actual Behavior

npm fails to install React dependency

### Steps to Reproduce (including precondition)

run: `npm i -g nyaovim` using node -v `7.2` and using neovim `0.1.7`

### Screenshot on This Problem (if possible)

![screen shot 2016-12-09 at 10 22 10 pm](https://cloud.githubusercontent.com/assets/1900735/21070894/025fa9b8-be5e-11e6-9834-c980b5d18d67.png)

### Your Environment

- OS: MacOS Sierra 10.12.2 Beta (16C53a)
- NyaoVim version: nyaovim@0.0.22
- `nvim` version: 0.1.7
- Keyboard layout: mac
- Linux: Window manager: N/A

**Comment by rhysd** [comment]
Yeah, it's intentional. NyaoVim uses [flux](https://github.com/facebook/flux) with Polymer. And some APIs of flux require React. It's because flux add React as peer dependency. However, NyaoVim doesn't use the APIs. So NyaoVim doesn't need the peer dependency.

**Comment by mdxprograms** [comment]
ahh gotcha. That stinks that it's so tightly coupled but I guess since that's what it was initially created for it defaults. Closing since it still works as expected! Thanks for the explanation. 👍
