### ISSUE TITLE
NyaoVim is unable to run

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#118]
NyaoVim is unable to run with errors

`main/browser-config.ts(9,30): error TS2694: Namespace 'Electron' has no exported member 'BrowserWindowOptions'.`

### Expected Behavior

should start ok

### Actual Behavior
unable to start
<img width="687" alt="2017-06-12 7 04 17" src="https://user-images.githubusercontent.com/4080524/27031226-00fb1514-4fa2-11e7-8647-5cdf49c38c08.png">

### Steps to Reproduce (including precondition)
- git clone https://github.com/rhysd/NyaoVim.git
- cd NyaoVim
- npm install
- npm start

### Your Environment

- OS: OSX
- NyaoVim version: 0.0.22
- `nvim` version: not installed yet

**Comment by rhysd** [comment]
I think Electron 1.6.10 causes this problem. It contains official type definitions and they are different from ines in DefinitelyTyped. We need to fix version to 1.6.9 for now.

**Comment by rhysd** [comment]
I addressed this in 748c2aa. Please `git pull` in cloned NyaoVim repo and `npm install` again.

**Comment by haifengkao** [comment]
Your fix doesn't work. I have to set Electron to 1.6.8 and fix every module versions in `package.json` to make `npm start` run without any errors.
I think it is better to add `package-lock.json` to avoid any similar issues in the future. 
Please refer to https://github.com/rhysd/NyaoVim/pull/119

**Comment by rhysd** [comment]
I fixed compilation error problems due to new official type definitions in 59e2199f14e8350a42bf3761e7c4a7630c9321e0 and now compilable with Electron 1.7. I'll close this.
