### ISSUE TITLE
Scrolling up causes text to become scrambled

### ISSUE THREAD

**Issue by johnhamelink** [rhysd/NyaoVim#12]
Hi again,

When I scroll up, the text gets mixed in with what was at the top of the screen. This doesn't happen when scrolling down:

<img width="801" alt="screen shot 2015-12-31 at 18 55 18" src="https://cloud.githubusercontent.com/assets/101739/12067344/47659810-aff0-11e5-8dc4-048ca908ceb9.png">

The file in question: https://gist.github.com/johnhamelink/abfbfe91ef604522a0d2

**Comment by tex** [comment]
I see it too.

**Comment by rhysd** [comment]
I fixed filling scroll region on scroll down. (Scrolling window down means scrolling buffer up, it's confusing a bit.)
In my environment, this is fixed `neovim-component@0.2.7`.

Could you check this after re-installing `nyaovim`?

**Comment by johnhamelink** [comment]
Yep, works well now, thanks :+1:
