### ISSUE TITLE
strange white line randomly appears on screen

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#122]
There is a strange white line

### Expected Behavior
<img width="793" alt="2017-06-21 5 07 58" src="https://user-images.githubusercontent.com/4080524/27376279-33f64b56-56a4-11e7-9808-5ac625d4f695.png">

### Actual Behavior
<img width="803" alt="2017-06-21 5 04 17" src="https://user-images.githubusercontent.com/4080524/27376129-cf1fa272-56a3-11e7-8d04-d275c4006060.png">

### Steps to Reproduce (including precondition)
edit any files with NyaoVim
I have tested with Electron 1.6.6 (https://github.com/haifengkao/NyaoVim-Unofficial/releases/tag/0.0.6)
both of them have the problem
The version with Electron 1.4.8 is working fine (https://github.com/haifengkao/NyaoVim-Unofficial/releases/tag/0.0.5)

### Your Environment

- OS: OSX 10.13

**Comment by haifengkao** [comment]
Electron 1.6.8 doesn't have this issue

**Comment by rhysd** [comment]
yeah, it's reproducible in my environment also. Chromium version update seems to cause this issue. So 1.6.8 does not cause this error.

Reported: https://github.com/rhysd/neovim-component/issues/44
