### ISSUE TITLE
Prevent nyaovim from opening Developer tools and .vimrc when launched from a dock launcher

### ISSUE THREAD

**Issue by skjorrface** [rhysd/NyaoVim#124]
This is not quite an issue with nyaovim itself but with nyaovim + gentoo + gnome desktop environment. If I launch nyaovim via terminal by just typing "nyaovim" everything works fine and nyaovim opens correctly; if I add a launcher to my dock with the command "nyaovim" then nyaovim opens my .vimrc file and developer tools without asking for it... How can I prevent this behaviour, it's quite boring to open nyaovim from the terminal all the time, thanks beforehand.

**Comment by rhysd** [comment]
I don't know the difference between from the dock and from a command line. So I can't say nothing. But setting command `NODE_ENV=production nyaovim` to doc icon may solve this problem.

And please do not ignore template next time.

**Comment by skjorrface** [comment]
Thanks @rhysd, that actually fixed the problem. Sorry, I (erroneously) thought it would be excessive to follow that accurate template for such a simple problem, I didn't mean to upset you. Anyways another thing I noticed is that a lot of shortcuts such Shift+Ctrl+I, Ctrl+I and so forth are totally ignored. I think electron has serious problems with gnome desktop environment lol
