### ISSUE TITLE
`cmd+v` Paste not working in the command mode

### ISSUE THREAD

**Issue by zhujinxuan** [rhysd/NyaoVim#125]
When I try to paste a vim command after `:`, I find `cmd+v` does not work.  In the vim command line, `cmd+v` only insert a `v` in the command line.

Also `cmd+v` does not work in the insert mode.  When I type `cmd+v` in the insert mode, it will insert a text as `<D-v>`

Thanks a lot for developing NyaoVim

**Comment by skjorrface** [comment]
Have you tried with <cmd+shift+v>?

**Comment by zhujinxuan** [comment]
I tried.  But it does not work

**Comment by rhysd** [comment]
Could you try out `disable-meta-key` attribute of `<neovim-editor>` element? This is a problem who handles key input.

1. Application window (for handling OS native shortcut like `Cmd+v`)
2. Neovim

By default, NyaoVim passes all inputs to Neovim (selecting 2.). By specifying the attribute, NyaoVim will choose 1. as its behavior.

https://github.com/rhysd/neovim-component#neovim-editor-properties

**Comment by zhujinxuan** [comment]
It works.  Thank you.
