### ISSUE TITLE
Feature Request: Option to start in fullscreen

### ISSUE THREAD

**Issue by esniper** [rhysd/NyaoVim#126]
Would be great to have a startup option that automatically launched each new instance in fullscreen.

**Comment by rhysd** [comment]
It's already supported.

Please make `browser-config.json` in `~/.config/nyaovim` with below contents

```json
{
  "window_options": {
    "fullscreen": true
  }
}
```

Doc: https://github.com/rhysd/NyaoVim/blob/master/docs/browser-config.md
