### ISSUE TITLE
Question: How to disable font-smoothing anti aliasing 

### ISSUE THREAD

**Issue by quenode** [rhysd/NyaoVim#128]
Hi All,

How to disable  font smoothing / antialiased fonts, 
Probably some line in nyaovim .config/nyaovim/nyaovimrc.html 
like "  -webkit-font-smoothing: none;" but not sure where
Help :)
I am using os x if that counts

**Comment by rhysd** [comment]
NyaoVim renders screen on `<canvas>`. I guess we can do it with passing `antialias: false` to second argument of `getContext()`

I think I can add a new option for this. But currently unable to specify it from outside.

**Comment by quenode** [comment]
Thank you so much :) @rhysd

**Comment by rhysd** [comment]
ah, `antialias` option is only for `webgl` renderer. So we need to investigate other way to make font not-smoothing...
