### ISSUE TITLE
Problem installing on Ubuntu

### ISSUE THREAD

**Issue by ElGoreLoco** [rhysd/NyaoVim#13]
I think this is a debian problem in general, but I have only tried installing on Elementary OS and Linux Mint.

When I install  it says:
```
> electron-prebuilt@0.36.2 postinstall /usr/local/lib/node_modules/nyaovim/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0
```

I don't know if there's something wrong with my systems or with the code. I don't usually use npm.

**Comment by rhysd** [comment]
What is the node version in your environment?

Node.js grows rapidly.  Node.js packaged for Debian may be too old.  FYI, I'm using [nvim](https://github.com/creationix/nvm) to use latest node.js.

**Comment by ElGoreLoco** [comment]
It says `v0.10.25`. I don't know if I should upgrade.

**Comment by ElGoreLoco** [comment]
I installed the latest version of node and io.js with nvm and now I can install nyaovim fine and run it. But when I close the terminal and open another one, the nyaovim command doesn't work anymore.

**Comment by rhysd** [comment]
If the npm error is resolved by newer node.js binary,  I think previous node version was too old.

> the nyaovim command doesn't work anymore.

I can say nothing from just 'doesn't work'.  Could you describe more detail?

**Comment by ElGoreLoco** [comment]
I run `nyaovim` and it says:
```
zsh: command not found: nyaovim
```
But when I run `npm list` it shows as it's installed and the configurations files in `.config/nyaovim/` are all there.

**Comment by rhysd** [comment]
Did you install `nyaovim` again?  `npm` is bundled with node.js.  So when you change the version of node.js,  you need to install package again.  You can check current installed package by `npm -g list`.

**Comment by ElGoreLoco** [comment]
I reinstalled it like four times. When I get home I will send you more information.

**Comment by rhysd** [comment]
Thank you for confirmation!

**Comment by ElGoreLoco** [comment]
It's a pleasure! I love what you are doing to Neovim so I hope I can help :)

When I install it just by running `npm install -g nyaovim` I get this:
```
npm http GET https://registry.npmjs.org/nyaovim
npm http 304 https://registry.npmjs.org/nyaovim
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/nyaovim'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/nyaovim']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/nyaovim',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/nyaovim',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.19.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nyaovim"
npm ERR! cwd /home/jorge
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/nyaovim
npm ERR! fstream_path /usr/local/lib/node_modules/nyaovim
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/nyaovim'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jorge/npm-debug.log
npm ERR! not ok code 0
```

It says that I could try running it as root, so I do it. `sudo npm install -g nyaovim`:
```
[a lot of "npm http GET" and an url like the ones below]
npm http 304 https://registry.npmjs.org/jsonpointer/2.0.0
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/is-property

> electron-prebuilt@0.36.2 postinstall /usr/local/lib/node_modules/nyaovim/node_modules/electron-prebuilt
> node install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
```
So here is when I freak out, because I updated node and it's not working.

Then I think that maybe it has something to do with installing it globally, so I install without the `-g` tag. `npm install nyaovim`:
The log is exactly the same as the last one with `sudo`.

And here is what I discovered: when I run `nvm install node` and right after (it only works if I do it in the same terminal) I run `npm install -g nyaovim`, it installs perfectly fine. And then I can run `nyaovim` perfectly too. I don't know if this the way it's supposed to work, or if I am simply a noob xD, but this is what happens.

OK, so now I have nyaovim installed, perfect. I close the terminal and open another one and running `nyaovim` doesn't work. It says:
> zsh: command not found: nyaovim

I just don't know what to say xD

I think the first problem installing is a problem of `nvm`. The second I don't really know because it's too weird for me.

I hope it helps all of this :)

**Comment by rhysd** [comment]
How did you install node.js?
The reason why global install failed is that `bin` path for node packages is not in `$PATH`.  It seems that you installed node.js to `/usr/local`, but I think that `sudo` doesn't use `/usr/local` and uses old `node` binary (you can check the version with `sudo node --version`).  So `sudo` can't be used.
If you omit `-g` on install, `npm` installs package locally and `$PATH` doesn't work for it.  Please see npm manual.

**Comment by ElGoreLoco** [comment]
I was installing with nvm. But apparently it doesn't work. Now searched for a ppa or something like that and I found [this](https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager). Now everything is working.

Sorry for making this a nodejs issue instead of a nyaovim issue and thanks for helping.

**Comment by wsdjeg** [comment]
I also failed to install this proj,here is my install info my os is ubuntu 15.10
![2016-02-16 00-39-26](https://cloud.githubusercontent.com/assets/13142418/13054693/1b50ed4a-d446-11e5-9b01-7fa79c6ed70e.png)

**Comment by rhysd** [comment]
@wsdjeg 

From your screenshot:

> sh:  1: node: not found

Did you ensure `node` command exists?  Binary name of Node.js on Ubuntu may be `nodejs` because  it is too old.  You need to install latest Node.js in other way.

**Comment by wsdjeg** [comment]
now most time I use neovim in terminal ,but I will try more with this project,thanks for you reply

**Comment by rhysd** [comment]
:smiley:

**Comment by bimlas** [comment]
Same issue here: Node is installed, but `node` binary doesn't exists, just `nodejs`. `ln -s /usr/bin/nodejs /usr/bin/node` solved the install.
