### ISSUE TITLE
No argument possible

### ISSUE THREAD

**Issue by vincentkosciuszko** [rhysd/NyaoVim#137]
Neovim work fine but nyaovim don't use the argument I pass. When I do this `nyaovim .` it open this folder : `C:\Users\Vincent\AppData\Roaming\NyaoVim`.

When I use `nvim .` it open the current dir. 

- OS: Window 10
- NyaoVim version: Last
- `nvim` version: Last
- Keyboard layout: Azerty

**Comment by ndaman** [comment]
See [here](https://github.com/rhysd/NyaoVim/issues/142#issuecomment-470254909) for a workaround
