### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gnumoksha** [rhysd/NyaoVim#139]
Installation error

### Expected Behavior

Install NyaoVim

### Actual Behavior

NyaoVim is not installed

### Steps to Reproduce (including precondition)
```
$ npm install -g nyaovim
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'electron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.15.0-2-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "nyaovim"
npm ERR! cwd /home/tobias
npm ERR! node -v v8.9.3
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tobias/npm-debug.log
npm ERR! not ok code 0
```

### Your Environment

- OS: Debian GNU/Linux testing (buster)
- NyaoVim version: i don't know
- `nvim` version: NVIM v0.2.2
- Keyboard layout: English (US)
- Linux: Window manager: Gnome shell

### Additional Comments (if any)

```
$ cat ~/.npmrc
prefix=/usr/local/bin/npm
```

**Comment by neochar** [comment]
https://github.com/rhysd/NyaoVim/issues/127#issuecomment-392573556

**Comment by gnumoksha** [comment]
I'm going to close this because I do not have the environment to test.
