### ISSUE TITLE
page down/up, insert key are ignored

### ISSUE THREAD

**Issue by tex** [rhysd/NyaoVim#14]

**Comment by rhysd** [comment]
Thank you for your report.

I added missing special keys at neovim-component@0.2.6.  I already checked for function keys as below.

```vim
nnoremap <F8> :<C-u>echo 'hello, function key'<CR>
```

But I don't have a keyboard which can send `<Insert>`.  Could you check it after reinstalling `nyaovim` package?  Please be sure that `neovim-component` dependency is 0.2.6.

**Comment by tex** [comment]
fixed, thanks :-)

**Comment by rhysd** [comment]
Thank you for confirming.
