### ISSUE TITLE
Enable terminal UI

### ISSUE THREAD

**Issue by adelarsq** [rhysd/NyaoVim#17]
Terminal UI is disabled by default:
```
C:\Users\MyUser>nvim
Terminal UI disabled at compile time, ignoring console input
```
It's possible to enable the feature? So we can use both (terminal and GUI).

**Comment by rhysd** [comment]
I think it is a problem of Neovim.  I'm not using Neovim in Windows and I don't know how to handle it.  Could you ask this in Neovim community? (e.g. [gitter](https://gitter.im/neovim/neovim?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))

**Comment by rhysd** [comment]
Please note that `:terminal` works in Linux or OS X.  It may be Windows specific problem

**Comment by adelarsq** [comment]
Got it. I will request there.

**Comment by adelarsq** [comment]
Yeap. It's a NeoVim problem. I will close this issue.
