### ISSUE TITLE
When Nyaovim window goes inactive, it doesn't trigger FocusLost

### ISSUE THREAD

**Issue by fevin86** [rhysd/NyaoVim#28]

**Comment by rhysd** [comment]
FocusGain has the same issue.  Neovim frontend should care them.

**Comment by rhysd** [comment]
I shipped neovim-component 0.4.3 with fix for this issue.  Could you reinstall 'nyaovim' package with `npm install -g nyaovim`?

**Comment by fevin86** [comment]
The fix works. Thanks for your effort! :+1:
