### ISSUE TITLE
ctrl+Home and ctr+End do not work

### ISSUE THREAD

**Issue by tex** [rhysd/NyaoVim#31]
I expect to move cursor to begining or to end of document.
It works with the same configuration in vim and in neovim.

**Comment by rhysd** [comment]
I tried this and it worked fine as below.

```vim
nnoremap <C-End> :echo 'C-End!!'<CR>
```

I also checked the input log and it was correct:

![2016-02-27 23 19 28](https://cloud.githubusercontent.com/assets/823277/13373357/77a051fa-dda9-11e5-9857-4e6aff31dd83.png)

Could you tell me the version of NyaoVim and neovim-component packages?

**Comment by tex** [comment]
NyaoVim version 0.0.17
  electron : 0.36.9
  chrome : 47.0.2526.110
  node : 5.1.1
  v8 : 4.7.80.27

Also Shift-Insert in insert mode does not insert content of clipoard but it insterts string '<S-Insert>'.

**Comment by rhysd** [comment]
Could you `npm uninstal`l and `npm install` nyaovim again?

If it doesn't solve this issue,  please show me the debug log because I can't reproduce this.

1. Start NyaoVim with $ NODE_ENV=debug nyaovim. (Chrome DevTools will also start.)
2. Open 'console' tab of DevTools.
3. Enter the input which causes this issue.
4. Log includes 'Keydown event:' output and 'Input to neovim:' it shows keydown event for your input. Could you take a screenshot of the event value?

**Comment by tex** [comment]
I did the reinstalation.

After pressing Ctrl-End:

index.js:1587 Keydown event: KeyboardEvent {isTrusted: true}
index.js:1587 Keydown event: KeyboardEvent {isTrusted: true}
index.js:1613 Invalid key input on 'keydown':  Unidentified
index.js:2234 Focus changed: false

**Comment by tex** [comment]
And after Shift-Insert:

Keydown event: KeyboardEvent {isTrusted: true}
index.js:1587 Keydown event: KeyboardEvent {isTrusted: true}
index.js:1629 Input event: Event {isTrusted: true}
index.js:1622 Input to neovim: ":"
index.js:1393 Cursor is moved to (0, 840)
index.js:2228 Highlight is updated:  Object {fg: "#c0c0c0", bg: "#000040", bold: undefined, italic: undefined, underline: undefined…}
index.js:2083 drawText(): (0, 840) 1 Object {line: 35, col: 0}
index.js:1393 Cursor is moved to (11, 840)
index.js:1587 Keydown event: KeyboardEvent {isTrusted: true}
index.js:1622 Input to neovim: "<S-Insert>"
index.js:2083 drawText(): (11, 840) 10 Object {line: 35, col: 1}
index.js:1393 Cursor is moved to (121, 840)
index.js:2234 Focus changed: false

**Comment by tex** [comment]
After Shift-Insert:

Keydown event: KeyboardEvent {isTrusted: true}
index.js:1587 Keydown event: KeyboardEvent {isTrusted: true}
index.js:1629 Input event: Event {isTrusted: true}
index.js:1622 Input to neovim: ":"
index.js:1393 Cursor is moved to (0, 840)
index.js:2228 Highlight is updated:  Object {fg: "#c0c0c0", bg: "#000040", bold: undefined, italic: undefined, underline: undefined…}
index.js:2083 drawText(): (0, 840) 1 Object {line: 35, col: 0}
index.js:1393 Cursor is moved to (11, 840)
index.js:1587 Keydown event: KeyboardEvent {isTrusted: true}
index.js:1622 Input to neovim: "<S-Insert>"
index.js:2083 drawText(): (11, 840) 10 Object {line: 35, col: 1}
index.js:1393 Cursor is moved to (121, 840)
index.js:2234 Focus changed: false

**Comment by rhysd** [comment]
Thanks.

"Unidentified" key is input as `keydown` event.  Browser (Electron is based on Chromium) seems to fail to identify Home/End/Insert keys.  I can't fix this...

Could you tell me your OS?  I may be able to try.

**Comment by tex** [comment]
Arch Linux, 64bits

**Comment by rhysd** [comment]
Could you show the contents of `KeyboardEvent`?

**Comment by tex** [comment]
It is shown in my answer begining with "I did reinstallation".

**Comment by rhysd** [comment]
Ah, sorry I missed it because of one line.

**Comment by rhysd** [comment]
I saw the log.

It said `charCode` is `0` and `which` is `17` (`17` means "ctrl key only").  So browser totally failed to catch the key combination and NyaoVim can't know which key was pressed, sorry.
