### ISSUE TITLE
Underline doesn't display

### ISSUE THREAD

**Issue by stsievert** [rhysd/NyaoVim#34]
I have underline for incorrect spelling. This underline doesn't display in NyaoVim but displays in terminal neovim.

NyaoVim:
<img width="618" alt="screen shot 2016-02-29 at 8 59 49 pm" src="https://cloud.githubusercontent.com/assets/1320475/13416377/b26c5084-df27-11e5-81ca-573a24de5c1f.png">

neovim:
<img width="591" alt="screen shot 2016-02-29 at 9 00 18 pm" src="https://cloud.githubusercontent.com/assets/1320475/13416376/b056e872-df27-11e5-95f1-56b8d0dcd701.png">

**Comment by stsievert** [comment]
I've tested this further: if I run `hi SpellBad gui=underline` after opening NyaoVim, it underlines correctly. If I include the same command in the last line of `~/.config/nvim/init.vim`, NyaoVim doesn't pick up on it but terminal neovim does.

**Comment by rhysd** [comment]
Thank you for the investigation.

But I can say nothing before reproducing it because underlines are rendered correctly in my environment.  Could you tell me the Neovim configuration which can reproduce this issue?

**Comment by stsievert** [comment]
Turns out it's not an issue with NeoVim, it's an issue with my vim config. Opening a file with `neovim <file>` doesn't work but `neovim` then selecting from vim-startify highlights correctly. I'm closing this issue; I have to clean up my vim config.

**Comment by rhysd** [comment]
@stsievert 

Thank you for investigation :smile:
