### ISSUE TITLE
ctrl-c doesn't exit input mode

### ISSUE THREAD

**Issue by maverick2000** [rhysd/NyaoVim#37]
In insert mode pressing ctrl-c doesn't exit insert mode
### Expected Behavior

I expect it to act like hitting Esc, exiting insert mode

### Actual Behavior

stays in insert mode, if in the middle of a line it splits the line into 2

### Steps to Reproduce (including precondition)

enter insert mode
start typing
press ctrl-c

### Screenshot on This Problem (if possible)

<img width="269" alt="screenshot 2016-03-17 16 19 18" src="https://cloud.githubusercontent.com/assets/2840852/13839117/0c9c423a-ec5c-11e5-8f58-5b7fc65e466f.png">

### Your Environment

- OS: Mac OSX El Capitan 10.11.4 Beta (15E61b) 
- NyaoVim version: NyaoVim version 0.0.19
  electron : 0.36.11
  chrome : 47.0.2526.110
  node : 5.1.1
  v8 : 4.7.80.27
- `nvim` version: {Please write here}
- Keyboard layout: US

**Comment by rhysd** [comment]
This is a `keydown` event instance on Ctrl+c.

![2016-03-17 23 15 43](https://cloud.githubusercontent.com/assets/823277/13848669/3a43e56e-ec96-11e5-82e5-420de7341f39.png)

It seems that `key` is wrong although `keyCode` is correct.

**Comment by rhysd** [comment]
I didn't know that `KeyboardEvent.key` is unsable (Chrome49 doesn't still enable it).  We might use `KeyboardEvent.code` but it's painful a bit...
OK, I'll add workaround

**Comment by rhysd** [comment]
@maverick2000 

I added a workaround at `neovim-component@0.5.2`.  Please uninstall `nyaovim` and install `nyaovim` again.

**Comment by maverick2000** [comment]
works now, thanks
