### ISSUE TITLE
paste breaks format

### ISSUE THREAD

**Issue by inspectahstack** [rhysd/NyaoVim#38]
When I paste multi line code from the browser into nyaovim it breaks the formatting regardless of 'set paste'
### Expected Behavior

I expect it the text to look like the one I pasted instead of everything on a single line
### Actual Behavior

All the text is paste into a single line

### Steps to Reproduce (including precondition)

grab some text like this
<img width="340" alt="screenshot 2016-03-17 16 22 25" src="https://cloud.githubusercontent.com/assets/2840852/13839232/c3f4e43c-ec5c-11e5-92d9-d80383058a70.png">

from 
http://docs.ansible.com/ansible/playbooks_prompts.html

open nyaovim and enter insert mode
paste in the text from your clipboard

### Screenshot on This Problem (if possible)

<img width="792" alt="screenshot 2016-03-17 16 25 45" src="https://cloud.githubusercontent.com/assets/2840852/13839252/ea3f09b0-ec5c-11e5-8f09-fdbe3e53395f.png">

### Your Environment

- OS: Mac OSX 10.11.4 Beta (15E61b)
- NyaoVim version: NyaoVim version 0.0.19
  electron : 0.36.11
  chrome : 47.0.2526.110
  node : 5.1.1
  v8 : 4.7.80.27
- Keyboard layout: US

**Comment by rhysd** [comment]
I can't reproduce this in my environment.

![tmp](https://cloud.githubusercontent.com/assets/823277/13850090/eacbf8e0-ec9b-11e5-9e8c-ea62842fcd40.gif)

Could you check below?

- Can you reproduce this with `nvim` in terminal?
- Could you try `:set paste` before pasting it with `p`?

**Comment by maverick2000** [comment]
The difference is I was pasting with `ctrl-v` which preserves the formatting in nvim but doesn't in nyaovim.  Using `p` works in nyaovim.  So the real issue is pasting does not preserve formatting using `ctrl-v`

**Comment by rhysd** [comment]
@maverick2000 

Hm, could you tell me exact sequence?  I need to reproduce it to fix.

**Comment by maverick2000** [comment]
Sure

1. go to browser and copy the snippet using `cmd-c`
2. open nyaovim
3. enter insert mode
4. paste using `cmd-v`

If I paste using `p` it works fine

**Comment by zhranklin** [comment]
The same problem on my mac!
Now I would like to set
`imap <c-v> <esc>"+p`
and use `ctrl-v` for pasting
