### ISSUE TITLE
Alt + shift opens the menu when I change keyboard layout

### ISSUE THREAD

**Issue by code-hunger** [rhysd/NyaoVim#41]
### Situation
I use <kbd>setxkbmap</kbd> to switch keyboard layouts with <kbd>alt + shift</kbd>

### Actual Behavior
The same shortcut opens the "edit" menu in the editor and redraws screen twice
(once with a full white background and then it fixes itself with the menu rendered).

### Expected behaviour
Just the layout to be changed, nothing more.

### Issue
Is there a way to prevent this? E.g. use instead a `:set guimenu` option like in gVim?

### Your Environment

- OS: Arch linux
- NyaoVim version: Git says pre-alpha-61-g6c31c3c
- `nvim` version: 0.1.2
- Keyboard layout: Both on a US and a cyrillic keyboard layout
- Linux: Window manager: Awesome WM

**Comment by rhysd** [comment]
I stopped hiding menu automatically.  It prevents handling Alt key, I think.  And I also add `show_menubar` config to `browser_config.json` in order to hide menubar (not auto-hide).
