### ISSUE TITLE
Electron caption

### ISSUE THREAD

**Issue by idoo** [rhysd/NyaoVim#44]
Wrong caption

### Expected Behavior

NyaoVim

### Actual Behavior

Electron

### Steps to Reproduce (including precondition)

just open this app

### Screenshot on This Problem (if possible)

http://take.ms/OfVkc

### Your Environment

- OS: Any
- NyaoVim version: last one
- `nvim` version: 0.13

**Comment by rhysd** [comment]
Yes, I also noticed this.  However, this is an restriction of Electron when using `electron-prebuilt` to launch an app.

We can change app icon in dock at runtime but can't change caption.

**Comment by haifengkao** [comment]
I made a [nyaovim.app](https://github.com/haifengkao/NyaoVim/releases).
You may check it out.
The release size after zipped is 53MB. Is it possible to reduce its size? (MacVim is only 7MB)

**Comment by rhysd** [comment]
@haifenhkao 

Please add caption 'THIS IS NOT AN OFFICIAL RELEASE' to your release note in order to avoid confusion.

It's not possible to reduce size.  Please check electron-prebuilt release size.  We cannot reduce size less than it.

**Comment by rhysd** [comment]
I closed this because it can't be fixed.

**Comment by haifengkao** [comment]
@rhysd I was hoping that you are going to release it. 
I can upload the app to homebrew if you like.

**Comment by rhysd** [comment]
OK, I'll release next version, please be patient.  Please note that this application is on pre-alpha stage until 0.1.0 is released.

**Comment by rhysd** [comment]
I need to add undercurl fix and some cleanup before release.
