### ISSUE TITLE
Doesn't render screen when Neovim shows message on start up

### ISSUE THREAD

**Issue by planaria** [rhysd/NyaoVim#5]
nyaovim コマンドにパラメータを与えず起動すると正常に動作しますが、
$ nyaovim test.cpp
のようにファイル名を与えると以下の現象が発生します。

1. 真っ白な画面が起動する
![image](https://cloud.githubusercontent.com/assets/1755069/12001722/cdd1821a-ab31-11e5-834d-49ea1092cece.png)

2a. エンターキーを押してから'a'を押すと終了する
2b. エンターキーを2回押すとファイルを正常に編集できる
2c. HJKLキーを何回押しても白い画面のまま
2d. Hキーを押してからエンターキーを押しても白い画面のまま
2e. Hキーを押してからエンターキーを2回押すとファイルを正常に編集できる
2f. Jキーを押してからエンターキーを1回押すとファイルを正常に編集できる

OS: Windows 10 Pro

**Comment by planaria** [comment]
C:\Users\[ユーザ名]\AppData\Local\nvim\swap 以下のファイルを削除すると、
ファイル名を指定しても正常に動作しました。
ウィンドウズの閉じるボタンで終了するとここにファイルが残ってしまうようです。

aキーを押すと終了するのは、裏で以下のような状態になっているのかもしれません。
（画像は、:e でファイルを開こうとした状態）
![image](https://cloud.githubusercontent.com/assets/1755069/12001867/70f0f73e-ab35-11e5-8017-431f541de048.png)

**Comment by rhysd** [comment]
報告ありがとうございます．
確かに起動時にメッセージが出る場合はうまくハンドリングできないと思います．
他のフロントエンドがどうやってハンドリングしてるのか調べる必要がありますね…

**Comment by rhysd** [comment]
ref: https://github.com/neovim/neovim/issues/3901

**Comment by rhysd** [comment]
I'll close this because

- NyaoVim now disables swapfile by adding -n to command line option here.
- And now g:nyaovim_version is defined by --cmd option hence users can see the variable instead of gui_running currently.

True fix would come with change of UI handling in Neovim 0.2.

**Comment by dmeehl** [comment]
What needs to change here? nyaovim is useless as a daily editor to me without backup/swap, so i'd like to start poking around.

Could you also point me to some direction on how to change and recompile nyaovim source? I am unfamiliar with the npm/electron environment.
