### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by tomleo** [rhysd/NyaoVim#50]
### Expected Behavior
Changing the font doesn't seem to have any effect. I tried both:

``` html
    <style>
      /* CSS configurations here */
    #nyaovim-editor: {
        font-family: "Input Mono", monospace;
    }
    </style>
```

And 

``` html
    <!-- Component tags here -->
    <neovim-editor id="nyaovim-editor" argv$="[[argv]]" font-size="8" font="Input Mono"></neovim-editor>
```

### Actual Behavior
When I open up developer tools and look at the computed font-family it says "Times New Roman".

### Steps to Reproduce (including precondition)
1. Open up gui in Ubuntu
2. Open up developer tools

### Your Environment

- OS: Ubuntu 15.04
- NyaoVim version: 0.0.19
- `nvim` version: 0.1.5-dev
- Keyboard layout: US
- Linux: Window manager: Unity

**Comment by rhysd** [comment]
`<neovim-editor>` renders screen using `<canvas>` so we can't specify font face with CSS.  Instead, [attribute is available](https://github.com/rhysd/neovim-component#neovim-editor-properties).
