### ISSUE TITLE
Error: spawn /usr/lib/node_modules/nyaovim/node_modules/electron-prebuilt/dist/electron ENOENT

### ISSUE THREAD

**Issue by rakshazi** [rhysd/NyaoVim#52]
Can't start nyaovim from docker image.
### Expected Behavior

Nyaovim starts
### Actual Behavior

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/nyaovim/node_modules/electron-prebuilt/dist/electron ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```
### Steps to Reproduce (including precondition)

Dockerfile:

``` docker
FROM alpine:latest
MAINTAINER Nikita Chernyi

RUN apk add --update nodejs git alpine-sdk libtool cmake automake m4 autoconf linux-headers unzip ncurses-dev python py-pip && \
  rm -rf /var/cache/apk/*

WORKDIR /tmp
ENV CMAKE_EXTRA_FLAGS=-DENABLE_JEMALLOC=OFF
ENV CMAKE_BUILD_TYPE=Release
ENV CLI_ARGUMENTS=/

RUN git clone https://github.com/neovim/libtermkey.git && \
  cd libtermkey && \
  make && \
  make install && \
  cd ../ && rm -rf libtermkey

RUN git clone https://github.com/neovim/libvterm.git && \
  cd libvterm && \
  make && \
  make install && \
  cd ../ && rm -rf libvterm

RUN git clone https://github.com/neovim/unibilium.git && \
  cd unibilium && \
  make && \
  make install && \
  cd ../ && rm -rf unibilium

RUN  git clone https://github.com/neovim/neovim.git && \
  cd neovim && \
  make && \
  make install && \
  cd ../ && rm -rf nvim

RUN npm install -g nyaovim

ENTRYPOINT nyaovim $CLI_ARGUMENTS
```

Commands:

``` bash
docker build .
docker run -ti --rm -e DISPLAY=$DISPLAY -e CLI_ARGUMENTS=`pwd`/Dockerfile -v /tmp/.X11-unix:/tmp/.X11-unix 4b5a5530a187
```
### Screenshot on This Problem (if possible)

Not needed, see error log above
### Your Environment
- OS: Ubuntu 15.10 amd64
- NyaoVim version: from NPM
- `nvim` version: builded from sources (master branch) today
- Keyboard layout: Doesn't matter
- Linux: Window manager: Compiz (default)
### Additional Comments (if any)

Please, explain me how to fix this problem?

**Comment by rakshazi** [comment]
@rhysd do you have any ideas?

**Comment by rhysd** [comment]
Hmm... It looks installing `electron-prebuilt` failed.  Could you check `node_modules/electron-prebuilt/dist` directory?  Does `electron` binary exist?

**Comment by talhaanees** [comment]
@rhysd electron-prebulit failed for me and dist directory doesn't exist

**Comment by rhysd** [comment]
`nyaovim` package already moves to `electron` package because `electron-prebuilt` was deprecated. Could you please paste the log of `npm install -g nyaovim`? Installing `electron` downloads Electron binary at `postinstall` hook. If the hook failed, `electron` package would be broken. In the case, please remove cache (`~/.npm`) and reinstall nyaovim.

**Comment by thebetterjort** [comment]
Error is a result of compiling failure from your FROM: alpine image.. Switch to node:7.10.1+ full image to get it working.
