### ISSUE TITLE
Scrolling only works on first pane

### ISSUE THREAD

**Issue by ukch** [rhysd/NyaoVim#56]
### Expected Behavior

When a window is split, scrolling using the mouse wheel should scroll either:
* the buffer beneath the cursor (preferred, in my view)
* the buffer containing the cursor

### Actual Behavior

Scrolling using the mouse wheel only scrolls the first pane.

### Steps to Reproduce (including precondition)

* Open nyaovim. Open a buffer containing enough text to be scrollable.
* Run `:spl` or `:vspl` a few times
* Try to scroll in each pane, using the scrol wheel.

### Your Environment

- OS: Debian Sid
- NyaoVim version: 0.0.19
- `nvim` version: 0.1.3
- Keyboard layout: UK
- Linux: Window manager: GNOME Shell 3.20.2

**Comment by htfy96** [comment]
Confirmed on my ArchLinux with nvim 0.1.5 and Gnome 3.20.3.

![anim](https://cloud.githubusercontent.com/assets/8121231/16980090/e9192e5c-4e96-11e6-9b12-01ab55bb5802.gif)

**Comment by rhysd** [comment]
@ukch @htfy96 

I fixed this in neovim-component v0.6.2.
please reinstall `nyaovim` package to reflect the fix.

![tmp](https://cloud.githubusercontent.com/assets/823277/17006843/d4c66306-4f1e-11e6-8b4c-980fce7aaf09.gif)
