### ISSUE TITLE
Missing icon on Linux

### ISSUE THREAD

**Issue by ukch** [rhysd/NyaoVim#57]
I have seen the [nyaovim icon](https://rhysd.github.io/images/NyaoVim.svg), but on Linux NyaoVim has a default icon.

### Screenshot on This Problem (if possible)

![screenshot from 2016-06-06 11-55-13](https://cloud.githubusercontent.com/assets/973865/15819914/d89c7b5a-2bdd-11e6-9114-8b9c263e5da0.png)
(this is from the application bar, but the same problem occurs on the dock - using [simple dock GNOME extension](https://extensions.gnome.org/extension/815/simple-dock/))

### Your Environment

- OS: Debian Sid
- NyaoVim version: 0.0.19
- `nvim` version: 0.1.3
- Keyboard layout: UK
- Linux: Window manager: GNOME 3.20.2

**Comment by rhysd** [comment]
In Linux, how to show icon is depending on desktop environment (e.g. in you environment, it looks GNOME).  So, it's hard to setup an app icon in all environments because I don't know how to do that.

**Comment by ukch** [comment]
Hi, according to electron-userland/electron-packager#128 this can be done by passing the `icon` argument to `BrowserWindow`, e.g.:

```js
new BrowserWindow({icon: NativeImage.createFromPath("/path/to/icon.png")})
```

**Comment by rhysd** [comment]
Nice! I'll add icon to window.
