### ISSUE TITLE
Pressing alt causes editor to flash

### ISSUE THREAD

**Issue by ukch** [rhysd/NyaoVim#59]
Pressing alt in Electron makes the menu bar appear. This causes the window to resize, and NyaoVim to re-draw the screen. This has the side-effect that pressing alt can cause the screen to flash white every time I press alt (which I do often, as I use ctrl-alt to switch workspaces).

### Expected Behavior

One of two options:
* Either, the screen is able to redraw without flashing white
* Or, toggling the menu bar does not force the screen to re-draw

### Actual Behavior

As above. The screen flashes white, causing me confusion and distress!

### Steps to Reproduce (including precondition)

* Open NyaoVim. Make sure 'set background=dark' is set.
* Press the alt key

### Your Environment

- OS: Debian Sid
- NyaoVim version: 0.0.19
- `nvim` version: 0.1.3
- Keyboard layout: UK
- Linux: Window manager: GNOME Shell 3.20.2

**Comment by rhysd** [comment]
Nice catch.  I didn't notice this because it depends on desktop environment.

**Comment by rhysd** [comment]
This fix will be included in v0.0.21
