### ISSUE TITLE
Add hot key to move focus to Vim screen

### ISSUE THREAD

**Issue by rhysd** [rhysd/NyaoVim#6]
After focus moving to other UI component on Electron from Neovim screen,  we need to click the screen to make focus back.
Although UI plugin should care the focus,  we should not expect plugin to handle focus perfectly.  (UI plugin may sometimes be not able to determine if focus should be moved to Neovim screen or not.)

So I think it is better to add hot key to focus Neovim screen.  User can make focus back to screen without using mouse.  User should be able to disable this hot key and change it to other key sequence.  I think **Esc key** is good for default.  It affects only when focus is NOT on Neovim screen.

I can implement the hot key by catching `window.addEventListener('keydown')`.

**Comment by justinmk** [comment]
:+1:  ESC is what I use for a similar purpose in VsVim and Vrapper.

**Comment by rhysd** [comment]
Thank you for your review :smile:

**Comment by rhysd** [comment]
I implemented this in da6e731aaef73977db1b103d2b500eaef2f7c125 and confirmed with [nyaovim-mini-browser](https://github.com/rhysd/nyaovim-mini-browser) plugin.  (I should add tests...)
