### ISSUE TITLE
unable to start the app

### ISSUE THREAD

**Issue by imshenshen** [rhysd/NyaoVim#60]
neovim/node-client/issues/15
neovim/node-client@31d085e279d852ba5e4cbeafdce56b87766e11e9

### Your Environment

- OS: OS X 10.11.5
- `nvim` version: NVIM v0.1.5-428-g5832809
NyaoVim version 0.0.19
  electron : 0.36.12
  chrome : 47.0.2526.110
  node : 5.1.1
  v8 : 4.7.80.27

**Comment by gwerbin** [comment]
Looking through the source code, it seems like this is the same problem as #53

**Comment by gwerbin** [comment]
I'm not sure what other changes were made in https://github.com/neovim/node-client/commit/31d085e279d852ba5e4cbeafdce56b87766e11e9, but my PR seems to fix the startup crash: https://github.com/rhysd/promised-neovim-client/pull/1

**Comment by rhysd** [comment]
I already merged you PR and published new version package.  Reinstalling `nyaovim` should fix this.  At least in my OS X environment it works well.  Thank you for your report and PR.
