### ISSUE TITLE
copy to system clipboard?

### ISSUE THREAD

**Issue by mattsawyer77** [rhysd/NyaoVim#61]
I'm wondering if it's possible to place text into the clipboard by selecting it in visual mode then doing cmd+c (I'm on a mac), similar to the way this works in [Neovim.app](https://github.com/rogual/neovim-dot-app). I'm assuming that either this isn't currently supported, or I've done something odd in my environment that is preventing this from working.

### Expected Behavior

the visual-mode selected text is not copied to the system clipboard.

### Actual Behavior

it should be copied to the system clipboard.

### Steps to Reproduce (including precondition)

1. copy some text from anywhere except Nyaovim into the system clipboard (for reference).
2. in Nyaovim, select some text with visual mode.
3. in the Nyaovim's Edit menu, click on Copy, or press cmd+c.
4. in any window, attempt to paste this text. You'll see that it's the text from step 1, not step 3.

### Your Environment

- OS: Mac OS 10.11.6 beta
- NyaoVim version: 0.0.19
- `nvim` version: v0.1.5-564-g6cee9d1
- Keyboard layout: Apple

**Comment by rhysd** [comment]
Sorry for confusing.  'Copy' or 'Cut' or something in app menu does not cooperate with Neovim itself.  We need to use Neovim's copy/paste mappings such as `y` for copying or `p` for pasting.
