### ISSUE TITLE
`hi SpellBad gui=undercurl` not working

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#68]
### Expected Behavior

should get undercurl
![2016-08-02 3 18 51](https://cloud.githubusercontent.com/assets/4080524/17320127/81e45332-58c4-11e6-9aa7-8b1ca7800a36.jpg)

### Actual Behavior
nothing is displayed
![2016-08-02 3 19 58](https://cloud.githubusercontent.com/assets/4080524/17320145/9b44b4de-58c4-11e6-95f2-18b914579dd3.jpg)

### Steps to Reproduce (including precondition)

`:hi SpellBad gui=undercurl`

**Comment by rhysd** [comment]
You're right.  Currently we ignore the `undercurl` font attribute from Neovim.

https://github.com/rhysd/neovim-component/blob/92df80862d42e7fe1062b39f1c2b81e22d3a622f/src/neovim/screen.ts#L214

We need to fix this (I need to know how to draw undercurl line on `<canvas/>`).

**Comment by rhysd** [comment]
![2016-08-06 20 03 17](https://cloud.githubusercontent.com/assets/823277/17456383/d9f87568-5c10-11e6-955a-be1e62510702.png)

I fixed this in ce540eb.
