### ISSUE TITLE
uimで変換中の文字が見えない

### ISSUE THREAD

**Issue by Kudzuyu** [rhysd/NyaoVim#72]
### 状況
Linuxで、uimという日本語入力ソフトを使っています。
nyaovim上で文字を打つと、変換前の文字が見えなくなってしまいます。Enterを押して確定させると見えるようになります。

### 動作環境

- OS: Antergos Linux(Arch Linux)
- NyaoVim version: (Linuxのリポジトリによると)0.0.20-1
- `nvim` version: v0.1.5-612-g335be42
- Keyboard layout: JP
- Linux: Window manager: Gnome3

### 追記

githubでissueするのはこれが最初なので、わかりづらかったらすいません。

**Comment by rhysd** [comment]
変換中の文字とおっしゃっているのは変換待ちのひらがな入力のことですよね？

変換待ちの入力は JavaScript から取れないため描画する手段がないのが現状です．これは NyaoVim がテキストエリアではなく canvas 上に描画しているのが原因でして，canvas に描画するのをやめるなどの大規模な変更を加えないかぎり修正するのは難しいです．

**Comment by Kudzuyu** [comment]
素早いお返事ありがとうございました。他に不満はないので、日本語を打つ時だけ別のエディタを使うなどして対応しようと思います。

**Comment by rhysd** [comment]
了解です．ご報告ありがとうございました．

**Comment by rhysd** [comment]
If anyone knows how to fix this, please ping me by comment here.
