### ISSUE TITLE
nvim.uiAttach is not a function

### ISSUE THREAD

**Issue by nwaywood** [rhysd/NyaoVim#75]
Since updating from `0.0.19` to `0.0.20`, nyaovim fails to loads

### Expected Behavior

Executing `$ nyaovim` in the command line should successfully launch nyaovim

### Actual Behavior

An error message appears that says `nvim.uiAttach is not a function`

### Steps to Reproduce (including precondition)

- Update to `0.0.20` by running `npm -g install nyaovim`
- Try to launch by running `$ nyaovim`

### Screenshot on This Problem (if possible)

<img width="808" alt="screen shot 2016-08-15 at 4 02 36 pm" src="https://cloud.githubusercontent.com/assets/3773641/17656838/c1e314fe-6301-11e6-955e-9f4defc584e9.png">

### Your Environment

- OS: OSX 10.10.5
- NyaoVim version: 0.0.20
- `nvim` version: v0.1.3-363-g2e2b575
- Keyboard layout: Query
- Linux: Window manager: N/A

**Comment by rhysd** [comment]
It's because remote msgpack API was updated.  Please update `nvim` to 0.1.5.

**Comment by nwaywood** [comment]
Yes updating to 0.1.5 fixed the issue, thank you.
