### ISSUE TITLE
cannot copy unicode characters

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#77]
unicode characters cannot be copied
### Expected Behavior

should see 中文 in system clipboard
### Actual Behavior

nothing is copied
### Steps to Reproduce (including precondition)

type a unicode char, e.g. 中文
in normal mode, use `V<ctrl-c>`
### Your Environment
- OS: OSX 10.11.6
- NyaoVim version: 0.0.20
- `nvim` version: 0.1.5

**Comment by rhysd** [comment]
I also could confirm this.  It seems that `<C-c>` is sent to Neovim properly, but Neovim looks not to handle it as 'Ctrl + C'.

I confirmed it with executing below code in DevTools:

```js
document.getElementById('nyaovim-editor').editor.getClient().input('<C-c>')
```

I need to investigate further.

**Comment by haifengkao** [comment]
This issue is really annoying. I can reproduce this issue with `yyp` as well. 
neovim doesn't have this issue.

Can you give me a hint about where to look at?

**Comment by haifengkao** [comment]
The problem is related to the version of electron. Electron 1.4.1 has this issue, but it has been fixed in 1.4.8

**Comment by haifengkao** [comment]
If I execute nyaovim with `npm start` command, the unicode characters can be copied correctly.
If I use `npm run pack:osx` to create a standalone app and run it, the unicode cannot be copied or pasted.

**Comment by haifengkao** [comment]
I am pretty sure that this issue is from neovim.

**Comment by rhysd** [comment]
thank you so much for investigation.
