### ISSUE TITLE
Can not boot nyaovim @nvim 0.1.6

### ISSUE THREAD

**Issue by ytac8** [rhysd/NyaoVim#78]
### Actual Behavior

when I type "nyaovim" in terminal, this message emerges in my terminal and I can't use nyaovim as shown in screenshot.
How can I fix it??

```
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-9.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
```

日本語でも書いておくと，neovimをアップデートしたところnyaovimが起動しなくなりました．
nyaovimコマンドを実行するとスクリーンショットのように真っ白な画面が出てきてしまいます．
また，ターミナルの方では上記のようなメッセージが出てきてしまいます．
少しぐぐってみましたが，よくわかりませんでした ．解決策等ありましたらお教えいただけると幸いです．

### Steps to Reproduce 

in terminal : type "nyaovim"

### Screenshot on This Problem 

<img width="1280" alt="2016-08-30 10 05 32" src="https://cloud.githubusercontent.com/assets/11435694/18072442/5774ef4a-6e99-11e6-8648-93e2ba88726a.png">

### Environment

- OS: OSX Elcapitan 10.11.6
- NyaoVim version: 0.0.20
- `nvim` version: 0.1.6
- Keyboard layout: US
- Linux: Window manager: ?

**Comment by rhysd** [comment]
ありがとうございます．0.1.6 はまだ試せていませんでした．こちらでも見てみます．

**Comment by rhysd** [comment]
手元では再現しませんでした．グラフィック系のエラーであれば Electron 本体のバグの可能性があるのですが， `nyaovim --version` すると Electron のバージョンは何になってますでしょうか？

**Comment by ytac8** [comment]
electronのバージョンは1.3.4でした
こちらがnyaovim --version したものになります
```
NyaoVim version 0.0.20
  electron : 1.3.4
  chrome : 52.0.2743.82
  node : 6.3.0
  v8 : 5.2.361.43
```

**Comment by BaronTommy** [comment]
私も同じ症状が発生しています。
`nyaovim --version`は同じ出力内容です
neovimは、0.16です
ソースからビルドも動きませんでした。
リリース版を利用しています。

出力内容です
```
index.js:2369 Line height is changed to '1.3'
events.js:141 Uncaught Error: write EPIPE
events.js:141 Uncaught Error: spawn nvim ENOENT
```

neovim単体での動作は確認済みです

**Comment by rhysd** [comment]
@BaronTommy そちらは症状が違うようです．`ENOENT` なのでログから察するに `nvim` が `$PATH` に含まれていなくてコマンドが見つからないと言われている気がするのですが，一応ご確認いただけませんでしょうか？

**Comment by BaronTommy** [comment]
@ytac8 さんと同様のエラーかと勘違いしていました。
すみません

```sh
tommyMac:~ Tommy$ which nvim
/usr/local/bin/nvim

tommyMac:~ Tommy$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/bin/nvim
```
このような状態です

@ytac8 さんとのエラーの種類が違う用でしたら
こちらに記述するより、別途issuesを立てます

実行下のはリリース版の**nyao**vimです

**Comment by rhysd** [comment]
ありがとうございます．新しい issue を立てていただけると助かります．日本語で大丈夫です．

**Comment by rhysd** [comment]
@ytac8 

エラーを見るにグラフィクス周りですので，ハードウェア依存の問題かもしれません．お使いの Mac についてもう少し詳細をいただけませんか？ (e.g. `iMac (27-inch, Late 2013)`)

**Comment by ytac8** [comment]
<img width="293" alt="2016-08-31 23 22 33" src="https://cloud.githubusercontent.com/assets/11435694/18132550/40d255d6-6fd2-11e6-9957-e46c6cc9066a.png">
<img width="332" alt="2016-08-31 23 23 21" src="https://cloud.githubusercontent.com/assets/11435694/18132551/40e3ac3c-6fd2-11e6-9481-ff100fc05872.png">

この辺りの情報で大丈夫でしょうか？

**Comment by rhysd** [comment]
ありがとうございます．ちょうどその機種を所有しておりますので，明日試せそうです．

**Comment by rhysd** [comment]
@ytac8 

遅くなりました．同じ環境で試してみたのですが，私の手元では再現しませんでした（#80 は起きました）。お手数ですが，ウィンドウは立ち上がっているとのことですので，DevTools でログを確認していただけませんでしょうか．`$ NODE_ENV=debug nyaovim` で DevTools が起動時に立ち上がるはずです．

**Comment by ytac8** [comment]
ありがとうございます．
devtoolsを見たところ以下の様なエラーが出ていました．

<img width="804" alt="2016-09-10 8 22 05" src="https://cloud.githubusercontent.com/assets/11435694/18405741/d3814798-772f-11e6-9108-943eda69d53a.png">

**Comment by rhysd** [comment]
ご確認ありがとうございます．どうやらコンソールに出ていたエラーは直接関係なく，#80 と同様のバグみたいですね．

**Comment by rhysd** [comment]
@ytac8 

v0.0.21 で直ったはずです．
ご確認ください．

**Comment by ytac8** [comment]
お返事遅くなってしまい申し訳ありません．
今日試してみたのですが，一番最初の状態と変わらず起動した後も白い画面のままでした．
`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-9.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 `
こちらのエラーも残っております．

`nyaovim --version`した結果は以下のとおりです．

```
NyaoVim version 0.0.21
  electron : 1.4.0
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

`$ NODE_ENV=debug nyaovim`もやってみたのですが，画面が白いままで何も出てこなかったです．

**Comment by rhysd** [comment]
ご確認ありがとうございます．DevTools のコンソールのほうには相変わらず 'prototype is not defined...' というエラーが出たままかどうかご確認願えませんでしょうか？ご報告いただいている描画周りのバグによるものなのかレンダラプロセス側の JS の問題なのか切り分けできてない状態です．

**Comment by ytac8** [comment]
原因がわからないのですが，
`NODE_ENV=debug nyaovim`
を実行してもconsoleが出てこない状態です…

**Comment by rhysd** [comment]
メニューアイテムの中の 'View' → 'Open Developper Tools' からも開けるのですが，試していただけませんでしょうか

**Comment by ytac8** [comment]
試してみたところ以下のよなメッセージが表示されました．
コンソールも見てみましたが何も書かれていないです…
<img width="805" alt="2016-09-18 18 01 55" src="https://cloud.githubusercontent.com/assets/11435694/18614459/1654d224-7dca-11e6-9fe0-c78327971704.png">

<img width="808" alt="2016-09-18 18 02 54" src="https://cloud.githubusercontent.com/assets/11435694/18614473/254be024-7dca-11e6-91d7-e925cb19a442.png">

**Comment by rhysd** [comment]
ありがとうございます．うーむ，レンダラプロセスが意図せず死んでいるようですね… Electron のバグの可能性がかなり高そうです

**Comment by ytac8** [comment]
なるほど…一度エレクトロンを入れ直してみます！

**Comment by lambdalisue** [comment]
本日久しぶりにインストールしたところ、同様の症状が発生しました。なお、electron などのバージョンも全く同じで devtools が機能していない点も同様です。ご報告まで

**Comment by rhysd** [comment]
ありがとうございます．うーん，Electron 1.4.0 なのが謎なんですよね… [package.json](https://github.com/rhysd/NyaoVim/blob/master/package.json#L46) では 1.3 を指定してるはずなんですが… とりあえず僕も 1.4 で見てみようと思います．

**Comment by lambdalisue** [comment]
`"electron-prebuilt": "1.3.5",` の間違いでは？

http://qiita.com/sotarok/items/4ebd4cfedab186355867#%E3%82%AD%E3%83%A3%E3%83%AC%E3%83%83%E3%83%88%E8%A1%A8%E8%A8%98-

**Comment by rhysd** [comment]
あー，いえ，`~1.3.5` が正しいですね．指摘ありがとうございます．修正しておきます．1.4 で動かないのは引き続き調べてみます．

**Comment by lambdalisue** [comment]
おねがいします :-)

**Comment by rhysd** [comment]
v0.0.22 で直ったと思いますので，一旦閉じます．もし万一直っていなければこの issue でメンションを飛ばしてください．

**Comment by lambdalisue** [comment]
治ってましたありがとうございます。:tada:

**Comment by ytac8** [comment]
治っていました！
有難うございます！
