### ISSUE TITLE
Pasting doesn't work if content contains vim commands 

### ISSUE THREAD

**Issue by MikaAK** [rhysd/NyaoVim#79]
`inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"`
and CMD + v causes
`inoremap   pumvisible() ? "\" : "\  ""`
### Expected Behavior

should paste in without running 
### Actual Behavior

uses codes as actual codes
### Steps to Reproduce (including precondition)

Use OS paste (cmd + v) or (ctrl + v) with `inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"` 
### Screenshot on This Problem (if possible)

![nyavim](https://cloud.githubusercontent.com/assets/4650931/18108110/d0ec1f4e-6ed8-11e6-8573-af1b6eafb120.gif)
### Your Environment
- OS: OSX (mac)
- NyaoVim version: 0.0.20
- `nvim` version: 0.1.5
- Keyboard layout: qwerty

**Comment by rhysd** [comment]
Cmd + v is sent to Neovim as `<D-v>` by default because Neovim can handle Cmd key.  You can use Cmd key for menu access from NyaoVim 0.0.21.  I'll ping you after releasing 0.0.21 here :smile:

**Comment by MikaAK** [comment]
Awesome thanks! When you mean menu access does that mean it's not forwarding it to neovim properly? I was having some issues getting my command key bindings to work as well though they worked with the alt key
