### ISSUE TITLE
Additional command-line arguments are ignored

### ISSUE THREAD

**Issue by V0idExp** [rhysd/NyaoVim#81]
Executing `nyaovim -u ~/.vimrc` seems to ignore the additional arguments, although the app starts and vim status line states `No matching autocommands`. Actually, giving whatever different string, say `nyaovim qwertyasdf` leads to same effect.

### Screenshot on This Problem (if possible)

![screen shot 2016-09-01 at 18 00 26](https://cloud.githubusercontent.com/assets/595098/18174480/03d4ba38-706e-11e6-9afd-ba493865beeb.png)

### Your Environment

- OS: OSX El Capitan
- `nyaovim --version`:
```
NyaoVim version 0.0.20
electron : 1.3.4
chrome : 52.0.2743.82
node : 6.3.0
v8 : 5.2.361.43
```
- `nvim` version: 0.1.5

**Comment by rhysd** [comment]
I found that passing two or more paths breaks PRC communication between nvim and frontend.  I sent PR and the problem will be fixed when it merged.

https://github.com/neovim/neovim/pull/5481

**Comment by rhysd** [comment]
As far as I confirmed, fixed version `nvim` does not reproduce this issue.

**Comment by rhysd** [comment]
The patch was merged and `nvim` HEAD now works without this problem.  Thank you for reporting this.
