### ISSUE TITLE
Fails launch with 'AVD_loader.cpp: failed to get a service for display 3' on macOS Sierra

### ISSUE THREAD

**Issue by Tehnix** [rhysd/NyaoVim#84]
### Expected Behavior

Nyaovim will launch as normal.

### Actual Behavior

Nyaovim starts with a blank screen and the terminal complains with, 

```
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3
```

### Steps to Reproduce (including precondition)

Run `nyaovim` in your terminal (most likely OS related, look under environment).

### Screenshot on This Problem (if possible)

![screenshot 2016-09-15 11 30 45](https://cloud.githubusercontent.com/assets/1189998/18545162/285b32c2-7b38-11e6-93c5-a05bd1446137.png)

### Your Environment

- OS: macOS Sierra (Version 10.12.0 Beta 16A313a)
- NyaoVim version: nyaovim@0.0.21
- `nvim` version: NVIM 0.1.6-dev
- Keyboard layout: Danish/DK
- Linux: Window manager: {Please write here}

### Additional Comments (if any)

I would imagine it has to do with changes in the next macOS/OS X, which should be coming out here in October. Worth noting that at the time of writing I should be on the most recent developer version.

If any other info is needed I'll be happy to provide it :)

**Comment by rhysd** [comment]
Hmm..., C++ level errors may be a bug of Electron. Could you try below and it also reproduce this error?

```
$ npm install -g electron
$ electron
```

**Comment by Tehnix** [comment]
You are totally right! It seems electron complains about the same, but it at least still shows something in the window.

Strangely when searching the issues nothing came up, but it seems related to #78 (maybe?) which I unfortunately can't read much of since it's in Japanese :x 

It might be that the `AVD_loader` error is not really the problem. In any regard I'm getting a completely blank screen, and opening dev tools along with reloading shows no data at all.

![screenshot 2016-09-15 12 03 20](https://cloud.githubusercontent.com/assets/1189998/18546088/6a1c807c-7b3c-11e6-89bc-c4d0fdc068d8.png)

**Comment by rhysd** [comment]
Thank you for your try! Could you report this to [electron/electron](https://github.com/electron/electron)?  I don't have an environment to reproduce.

Root cause of #78 is different from this because I could reproduce it.

**Comment by philk** [comment]
I get the same error on Yosemite 10.11.6. No additional output with `NODE_ENV=debug`

**Comment by rhysd** [comment]
Does 'Open Devloper Tools' menu item work?  If not, this may be the same as #53.

**Comment by rhysd** [comment]
#53 was fixed.  I guess this issue also can be closed.  If anyone finds this issue still be there, please ping me here.

**Comment by curiojeff** [comment]
New to Electron, trying to learn it. Mac OS Sierra 10.12.3. When I run my app from the console I get this error:
<code>
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 7 </code>

My Electron windows open and work, but the console hangs up until I control-C to get out of it. Help?! Besides this old thread, can't find any ref. to this problem anywhere online.
