### ISSUE TITLE
White Screen, and Enter doesn't clear it.

### ISSUE THREAD

**Issue by jordwalke** [rhysd/NyaoVim#85]
### Expected Behavior
Enter should clear white screen.
{Please write here}

### Actual Behavior
Does not clear white screen.
{Please write here}

### Steps to Reproduce (including precondition)
Open the app.
{Please write here}

### Screenshot on This Problem (if possible)

{Please write here}

### Your Environment

- OS: OSX
- NyaoVim version: `npm install nyaovim` today.
- `nvim` version: HEAD today
- Keyboard layout: USA
- Linux: Window manager: {Please write here}

### Additional Comments (if any)
I'm using [VimBox](https://github.com/jordwalke/VimBox)

The problem with this bug is that I can't even clear the white screen so that I can check the `:messages` to find out what the problem is. If Enter would clear the white screen, I could at least debug the issue.

**Comment by jordwalke** [comment]
FWIW, I can open `nvim` without any problems.

**Comment by jordwalke** [comment]
And even if I comment out my vimrc, which disables all my vim plugins, I still get a white screen:

```
nyaovim --version

NyaoVim version 0.0.21
  electron : 1.4.1
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45

```

**Comment by raacker** [comment]
I was about to make an issue! I'm facing same problem.

- OS: Linux-mint
- NyaoVim version: just installed
- nvim version: just installed
- Keyboard layout: Korean

Tried to update all components like npm or nodejs or anything, it still doens't work. 

Any idea?

**Comment by rhysd** [comment]
Is this the same as #53 ?

**Comment by raacker** [comment]
Oh Yes I guess. Looks same problem! I'll check out #53 comments.

**Comment by jordwalke** [comment]
Yes, leaving my comments there - will close this one.
