### ISSUE TITLE
Question: Is it possible to toggle fullscreen from Vimscript?

### ISSUE THREAD

**Issue by lambdalisue** [rhysd/NyaoVim#86]
I would like to toggle fullscreen by using [lambdalisue/vim-fullscreen](https://github.com/lambdalisue/vim-fullscreen).
So it is nice if nyaovim have **a way to toggle fullscreen from Vimscript** like [neovim-qt](https://github.com/lambdalisue/vim-fullscreen#with-neovim-qt)

**Comment by rhysd** [comment]
Yes, it's possible via msgpack RPC and JavaScript.  I'll show you the config.

**Comment by rhysd** [comment]
We can access window state with Electron API from JavaScript.

https://github.com/electron/electron/blob/master/docs/api/browser-window.md

To access to JavaScript environment from Vim script, we currently should use `nyaovim#call_javascript_function(func_name, args)`.

### 1. Write below JavaScript code to `~/.config/nyaovim/nyaovimrc.html`.

```html
<script>
window.toggleWindowFullScreen = function() {
  const win = require('electron').remote.getCurrentWindow();
  win.setFullScreen(!win.isFullScreen());
};
</script>
```

### 2. Call the runtime function from Vim script

```vim
:call nyaovim#call_javascript_function('toggleWindowFullScreen', [])
```


I think this is a bit too hacky.  So I'm considering to add a new runtime function `nyaovim#execute_javascript(code)` in next version.  It can run JavaScript directly from Vim script.

**Comment by lambdalisue** [comment]
Hum... I feel using `nyaovim#execute_javascript()` is too specialized while that function also require javascript code. Why don't you let users to send a message with `rpcnotify`? (or am I misunderstood the architecture?)

My willing is something like:

```vim
call rpcnotify(0, 'Fullscreen', 1) " Enable fullscreen
call rpcnotify(0, 'Fullscreen', 0) " Disable fullscreen
call rpcnotify(0, 'Fullscreen', -1) " Toggle fullscreen
" Additional
call rpcnotify(0, 'GuiFont', 'Ricty:h10')
call rpcnotify(0, 'Menu', 0)
" or whatever...
```

**Comment by rhysd** [comment]
> I feel using nyaovim#execute_javascript() is too specialized

I'm not thinking it's specialized, but it's not good idea to expose JavaScript layer to Vim script, it's too generic, I agree.

However, I won't implement fullscreen specific RPC function because there're many GUI related APIs and rendering process related APIs.  I don't want to re-implement them as RPC functions.

So, I want to suggest below API

  nyaovim#browser_window(method, args)

`method` is a name of method of `BrowserWindow` which I showed the link above.  And `args` is arguments for the method.  So toggling window can be implemented with it as following:

```vim
if nyaovim#browser_window('isFullScreen')
  nyaovim#browser_window('setFullScreen', [v:false])
else
  nyaovim#browser_window('setFullScreen', [v:true])
endif
```

Please note that NyaoVim doesn't intend that so many things're not done in Vim script.  You can always use JavaScript from `nyaovimrc.html` for GUI configuration with CSS or attribute of `<neovim-editor>` element.

**Comment by lambdalisue** [comment]
> Please note that NyaoVim doesn't intend that so many things're not done in Vim script. You can always use JavaScript from nyaovimrc.html for GUI configuration with CSS or attribute of <neovim-editor> element.

I see. It makes sense.

Thanks!

**Comment by rhysd** [comment]
Hmm... but my concern is that something can be done in Vim script only.  For example, mapping something to key sequence can be done in Vim script (without calling msgpack RPC API).  So, if we want to toggle fullscreen with some key mappings, it can be implemented with only JavaScript (although it can with RPC).

At least, I think `fullscreen` option should be reflected (it should be notified via UI RPC API).

**Comment by lambdalisue** [comment]
> At least, I think fullscreen option should be reflected (it should be notified via UI RPC API).

Then the world becomes more helpful ;-)

**Comment by rhysd** [comment]
Ah, I noticed that `'fullscreen'` option is only for MacVim, hence it's not possible to use the option in NyaoVim or other GUI frontend.  We need to provide our original API to control window state...
