### ISSUE TITLE
Can't map <S-Space>

### ISSUE THREAD

**Issue by ifsred** [rhysd/NyaoVim#88]
Hello, I am trying to migrate my nvim setup to nyaovim and one of the things that I can't config is `<S-Space>` mapping. I know that shift+space is problematic bind for some terminal emulators so I have no Idea how hard it will be to implement for electron.

### Expected Behavior

`map <S-Space>` to work

### Actual Behavior

`map <S-Space>` is ignored, regular map space is used

### Steps to Reproduce (including precondition)

`nnoremap <Space> <PageDown>`
`nnoremap <S-Space> <PageUp>`

### Your Environment

- OS: OSX 10.11.6 
- NyaoVim version: 0.0.22
- `nvim` version: 0.1.6-dev
- Keyboard layout: qwerty

**Comment by justinmk** [comment]
Sending `<S-Space>` to nvim should work, the GUI just needs to capture it. Verified by:

```vim
:nnoremap <S-Space> :echo 'sspc'<CR>
:call nvim_input('<S-Space>')
```

**Comment by rhysd** [comment]
@justinmk 

Thank you for the info.  I'll investigate this after #87 done.

**Comment by romgrk** [comment]
This is due to space key being of `length == 1` and a special key. Sent a PR over neovim-component repo.
