### ISSUE TITLE
Too long to open a big file

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#89]
It takes too long to open a big file.
nvim can open a big file in few secs.
But nyaovim takes a minute to open the same file.

### Expected Behavior
should open the file within 5 secs

### Actual Behavior

nyaovim takes a minute to open the file

### Steps to Reproduce (including precondition)

1. download the 40MB json file https://raw.githubusercontent.com/Fngi/taipower_MAPS/gh-pages/result.json
2. open it with nyaovim

**Comment by justinmk** [comment]
That's a Vim problem, nyaovim cannot help it.

**Comment by rhysd** [comment]
As @justinmk said, Vim is not good at handling large files.  Please try `nvim` in terminal to clarify the problem derives from backend (Vim) or frontend (NyaoVim).

**Comment by haifengkao** [comment]
You are right. Because I opened the file with `nyaovim` first,  `nvim` can open the same file in few secs. If I open the file with `nvim` first, `nvim` is very slow as well.

**Comment by rhysd** [comment]
@haifengkao Thank you for confirmation. :smiley:

**Comment by haifengkao** [comment]
@rhysd I am sorry. I was wrong again. nvim can open the same big file in few secs. 
But it didn't display the file content until I press ctrl-c.

**Comment by haifengkao** [comment]
If the plugins are removed, `nyaovim` can open the same big file in few seconds.

**Comment by haifengkao** [comment]
If the plugins are removed, `nyaovim` can open the same big file in few seconds.
If the plugins are added, `nyaovim` can also open the file in few seconds if users press `ctrl-c`. 
In my experiments, `nvim` and `nyaovim` can open a 200MB file in seconds without any problem.
