### ISSUE TITLE
Background is wrong on whitespace on scroll

### ISSUE THREAD

**Issue by johnhamelink** [rhysd/NyaoVim#9]
Hey there, thanks so much for starting this. I wanted to do this ages ago, but... well... life got in the way as usual!

Anyway, I wanted to log this bug: When I scroll down, all the whitespace looks like this:

<img width="802" alt="screen shot 2015-12-30 at 18 14 45" src="https://cloud.githubusercontent.com/assets/101739/12055081/58605292-af21-11e5-99c1-9ce985aace56.png">

**Comment by rhysd** [comment]
Thank you for your report.

Yes, in some case, I also confirmed that background color of scroll region was wrong.  I need to analyze notifications from Neovim while scrolling.
(Because of end of year,  this may take some time to fix...)

**Comment by rhysd** [comment]
I think this bug was fixed on neovim-component@0.2.5.

Could you reinstall `nyaovim` package and confirm the fix?  (Please ensure `neovim-component` version is 0.2.5 in dependencies).

**Comment by johnhamelink** [comment]
Yes this is fixed now, thanks! :)
