### ISSUE TITLE
Chinese display problem

### ISSUE THREAD

**Issue by shitfSign** [rhysd/NyaoVim#91]
- OS : win7 64  
- NyaoVim version:  0.0.22
- `nvim` version: NVIM v0.1.6-186-gfb18ab3  https://ci.appveyor.com/project/equalsraf/neovim
- font :  Menlo  line-height 1.5 font-size 11

![c787348d9a2f78a0a5236e6b27d5c065](https://cloud.githubusercontent.com/assets/2169956/19228005/52b38280-8ef3-11e6-83f3-e7c833de78d0.jpg)

![b6eaa881eae78cc388b43c1c056791fd](https://cloud.githubusercontent.com/assets/2169956/19228035/9ce14680-8ef3-11e6-82ae-95201dfadea1.jpg)

**Comment by shitfSign** [comment]
I tried the other version, it's normal.

**Comment by justinmk** [comment]
See also https://github.com/neovim/neovim/issues/5448

**Comment by rhysd** [comment]
@shitfSign Please do not remove default issue template.
