### ISSUE TITLE
incorrect display of unicode charactors

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#92]
### Expected Behavior
![2016-10-11 10 07 47](https://cloud.githubusercontent.com/assets/4080524/19273462/307f7676-8fff-11e6-928d-734615f9a121.jpg)

### Actual Behavior
![2016-10-11 10 03 12](https://cloud.githubusercontent.com/assets/4080524/19273330/bab80bba-8ffe-11e6-8c30-4fbbbcf63bbb.jpg)

### Steps to Reproduce (including precondition)

- create a txt file with the following content
```
阿弗德雷.齊默爾(Alfred E. Zimmern) 

他在他的經典之著《中立和集體安全》中說明:「人類之所以會發 生戰爭,不是因為人類是惡的或沒有國家社會意識的,而是因為國家讓我們成為保守的 而且是智慧有限的人們。」 
```
- open the file with nyaovim

### Your Environment

- OS: Mac OSX
- NyaoVim version: 0.0.22
- `nvim` version: NVIM v0.1.6-201-g4408431

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/5448

**Comment by haifengkao** [comment]
thanks
