### ISSUE TITLE
edit menu hot keys is not working again

### ISSUE THREAD

**Issue by haifengkao** [rhysd/NyaoVim#94]
The newest version of Nyaovim (0.0.22) maps the hot keys to something like `<D-c>` for copy, `<D-v>` for paste. The process is done by `input.ts` in `neovim-component`.
I don't think `setMenu` in `menu.ts` actually got any hot key events. 

### Expected Behavior
`cmd-c` should copy the text
`cmd-v` should paste the text

### Actual Behavior
The screen displays `<D-c>` and `<D-v>` instead.
If `disable-meta-key` is set in `nyaovimrc.html`, only `c` and `v` is displayed.

### Your Environment

- OS: OSX 10.11
- NyaoVim version: 0.0.22
- `nvim` version: NVIM v0.1.6-232-g5a61ff1

### Workaround
The workaround is to map the edit menu actions in `init.vim`.
I believe this behavior should be default.
``` vim
" neovim hotkey workaround {

" undo
nnoremap <D-z> :undo
xnoremap <D-z> <Esc>:undo
snoremap <D-z> <Esc>:undo
inoremap <D-z> <Esc>:undo
cnoremap <D-z> <Esc>:undo

" redo
nnoremap <S-D-z> :redo
xnoremap <S-D-z> <Esc>:redo
snoremap <S-D-z> <Esc>:redo
inoremap <S-D-z> <Esc>:redo
cnoremap <S-D-z> <Esc>:redo

" cut 
xnoremap <D-x> "+x

" select-all
nnoremap <D-a> ggVG
xnoremap <D-a> <Esc>ggVG
snoremap <D-a> <Esc>ggVG
inoremap <D-a> <Esc>ggVG
cnoremap <D-a> <Esc>ggVG

" copy
xnoremap <D-c> "+y

" paste - normal mode
nnoremap <D-v>  "+p

" paste - visual mode
" V is visual line mode
" v is visual mode
" ^v is visual block mode
" "_d means deleting the highlighted area
" to prevent vim from copying the area to the pasteboard
" the "_d trick doesn't work for visual block mode
" because the visual selection will disappear after "_d command
xnoremap <expr> <D-v> mode() ==# "^v" ? '"+p' : mode() ==# "v" ? '"_d"+P' : '"_d"+p'

" paste - insert mode
" gp will move cursor to the last of pasted content
inoremap <D-v>  <C-o>"+gp

" paste - command line mode
cnoremap <D-v>  <C-r>+

" }
```

**Comment by rhysd** [comment]
neovim-component v0.8.2 should solve this (at least in my environment it works again).  Could you update and try the package?

**Comment by haifengkao** [comment]
Yes, it works with disable-meta-key.
Thanks :100:
